//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCouture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personne
    {
        public int idPers { get; set; }
        public string nomPers { get; set; }
        public string prenomPers { get; set; }
        public string adressePers { get; set; }
        public string telPers { get; set; }
        public string emailPers { get; set; }
    }
}
